"""Canonical per-version recipe migration table.

Each entry in ``RECIPE_MIGRATIONS`` describes the surgical keyword changes
that were applied to the **bundled** recipe templates at a given version
boundary. The ``migrate_recipe`` runner uses this table to bring personal
recipes (user-edited copies generated by the setup wizard) up to date
without requiring the user to re-run the full wizard.

Format
------
``RECIPE_MIGRATIONS`` is a ``dict[str, list[TopicMigration]]`` keyed by
version string (``"0.3.17"``, etc.).  Each ``TopicMigration`` names a
recipe **topic** (matched by ``name`` field inside a ``topics:`` block)
and lists the keywords to remove and/or add.

A keyword is matched case-insensitively and with leading/trailing whitespace
stripped.  Only keywords **explicitly listed in ``remove``** are dropped;
any keyword the user added beyond the stale template is preserved.

Stale markers
-------------
``STALE_MARKERS`` is a ``dict[topic_name, set[keyword]]`` mapping that the
setup SKILL Branch 1 uses as a heuristic to detect whether a personal recipe
predates a known migration.  If any keyword in the set appears in the named
topic's keyword list, the recipe is considered stale for that version.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True, slots=True)
class TopicMigration:
    """Keyword changes for a single topic at a migration boundary."""

    topic_name: str
    """Exact topic ``name`` field to match (case-sensitive, strip whitespace)."""

    remove: list[str] = field(default_factory=list)
    """Keywords to remove from the topic (case-insensitive match)."""

    add: list[str] = field(default_factory=list)
    """Keywords to add if not already present (case-insensitive dedup)."""


# ---------------------------------------------------------------------------
# Migration table
# ---------------------------------------------------------------------------

# v0.3.17 — tightened the bundled setup SKILL's biomedical-pathology keyword
# list: dropped 'foundation model' (matches every ML paper, inflates scores),
# consolidated WSI variants. Ref: task 9.9 (CHANGELOG v0.3.17).
_V0_3_17: list[TopicMigration] = [
    TopicMigration(
        topic_name="biomedical-pathology",
        remove=[
            "foundation model",
            "vision-multimodal",
        ],
        add=[],
    ),
]

RECIPE_MIGRATIONS: dict[str, list[TopicMigration]] = {
    "0.3.17": _V0_3_17,
}

# ---------------------------------------------------------------------------
# Stale-detection heuristic
# ---------------------------------------------------------------------------

# If ANY of these keywords is present in the named topic, the personal recipe
# is considered stale for the corresponding version and should be migrated.
STALE_MARKERS: dict[str, dict[str, set[str]]] = {
    "0.3.17": {
        "biomedical-pathology": {"foundation model", "vision-multimodal"},
    },
}


__all__ = ["RECIPE_MIGRATIONS", "STALE_MARKERS", "TopicMigration"]
