"""Sandbox + smart mock shim infrastructure for the v0.3.38 SKILL bash lint.

The comprehensive subprocess lint (D-9.38.6, plan §15.3 task 9.100)
executes every fenced ``bash`` block of every shim-using SKILL in a
mocked HOME tree to verify the source-or-die bootstrap stanza + the
subsequent ``paperwiki <subcommand>`` invocations actually work
end-to-end. This module materializes that tree.

What the sandbox provides:

- ``$HOME/.local/bin/paperwiki`` — a smart mock shim that dispatches
  per-subcommand. Returns plausible stub output (valid JSON for
  ``diagnostics``, plain text for everything else) and exits 0.
- ``$HOME/.local/lib/paperwiki/bash-helpers.sh`` — the **real**
  helper file copied byte-for-byte from ``lib/bash-helpers.sh`` so
  the source-or-die stanza succeeds.
- ``$HOME/.config/paper-wiki/recipes/daily.yaml`` — minimal valid
  recipe; ``secrets.env`` — empty placeholder.
- ``$HOME/.claude/plugins/cache/paper-wiki/paper-wiki/0.3.38/`` —
  stub plugin cache containing a no-op ``hooks/ensure-env.sh`` and a
  ``recipes/daily.yaml`` so the digest SKILL's bundled-template
  fallback path finds something.
- ``$HOME/Documents/Paper-Wiki`` — empty stub vault for SKILLs that
  shell out ``ls -d ~/Documents/*Vault*``-style commands.

The smart shim's per-subcommand output is intentionally minimal —
just enough that SKILL bash blocks that pipe ``paperwiki diagnostics``
through ``jq``, or branch on ``paperwiki status``'s exit code, can
proceed without crashing.
"""

from __future__ import annotations

import shutil
import stat
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
_HELPER_SOURCE = _REPO_ROOT / "lib" / "bash-helpers.sh"

#: Plugin-cache version we pretend is installed in the sandbox. Matches
#: the v0.3.38 helper tag so ``paperwiki_resolve_plugin_root`` finds the
#: stub cache dir at the expected version path.
SANDBOX_PLUGIN_VERSION = "0.3.38"

_SHIM_TEMPLATE = """#!/usr/bin/env bash
# Smart mock paperwiki shim for the v0.3.38 subprocess-lint sandbox.
# Per D-9.38.6 — emits documented stub output per subcommand so SKILL
# bash blocks that invoke `paperwiki <X>` can run end-to-end without
# the real venv/runner. This file is regenerated by build_sandbox()
# on every test session — DO NOT edit live.
set -euo pipefail

cmd="${1:-}"
shift || true

case "$cmd" in
  diagnostics)
    cat <<'JSON'
{"venv": "ok", "shim_version": "v0.3.38", "mcp_servers": [], "status": "healthy"}
JSON
    ;;
  status)
    echo "paperwiki v0.3.38 (sandbox)"
    ;;
  digest|wiki-ingest|wiki-lint|wiki-compile|wiki-query|extract-images|migrate-recipe|migrate-sources|update|uninstall|gc-archive|gc-bak|where)
    echo "paperwiki $cmd: stub-mock $*"
    ;;
  "")
    echo "paperwiki: usage: paperwiki <subcommand> [args]" >&2
    exit 2
    ;;
  *)
    echo "paperwiki: stub-mock unknown subcommand '$cmd' $*" >&2
    ;;
esac
exit 0
"""

_STUB_ENSURE_ENV = """#!/usr/bin/env bash
# Stub ensure-env.sh for the v0.3.38 lint sandbox — no-op.
# Real ensure-env.sh bootstraps a venv + installs the bash helpers;
# in the sandbox both are pre-built by build_sandbox().
exit 0
"""

_MINIMAL_RECIPE = """name: sandbox-stub
sources:
  - name: arxiv
    config:
      categories: [cs.AI]
scorer:
  name: composite
  config:
    topics:
      - name: vlm
        keywords: [foundation model]
reporters:
  - name: markdown
    config:
      output_dir: ./out
"""

_EXEC_BITS = stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH


def build_sandbox(tmp_path: Path) -> Path:
    """Materialize a sandbox HOME tree under ``tmp_path``.

    Returns the path to use as the child process's ``HOME`` env var.
    """
    home = tmp_path / "home"
    home.mkdir(parents=True, exist_ok=True)

    # ~/.local/bin/paperwiki — smart mock shim (executable).
    bin_dir = home / ".local" / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)
    shim = bin_dir / "paperwiki"
    shim.write_text(_SHIM_TEMPLATE, encoding="utf-8")
    shim.chmod(shim.stat().st_mode | _EXEC_BITS)

    # ~/.local/lib/paperwiki/bash-helpers.sh — real helper from repo.
    lib_dir = home / ".local" / "lib" / "paperwiki"
    lib_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(_HELPER_SOURCE, lib_dir / "bash-helpers.sh")

    # ~/.config/paper-wiki/{recipes/daily.yaml, secrets.env}.
    config_root = home / ".config" / "paper-wiki"
    (config_root / "recipes").mkdir(parents=True, exist_ok=True)
    (config_root / "recipes" / "daily.yaml").write_text(_MINIMAL_RECIPE, encoding="utf-8")
    (config_root / "secrets.env").write_text(
        "# sandbox placeholder — no real secrets here\n", encoding="utf-8"
    )

    # ~/.claude/plugins/cache/paper-wiki/paper-wiki/<VERSION>/ — stub
    # plugin cache. Provides hooks/ensure-env.sh (no-op) + recipes/
    # for digest's bundled-template fallback path.
    cache = (
        home
        / ".claude"
        / "plugins"
        / "cache"
        / "paper-wiki"
        / "paper-wiki"
        / SANDBOX_PLUGIN_VERSION
    )
    cache.mkdir(parents=True, exist_ok=True)
    (cache / "hooks").mkdir(exist_ok=True)
    stub_ensure = cache / "hooks" / "ensure-env.sh"
    stub_ensure.write_text(_STUB_ENSURE_ENV, encoding="utf-8")
    stub_ensure.chmod(stub_ensure.stat().st_mode | _EXEC_BITS)
    (cache / "recipes").mkdir(exist_ok=True)
    (cache / "recipes" / "daily.yaml").write_text(_MINIMAL_RECIPE, encoding="utf-8")
    (cache / "lib").mkdir(exist_ok=True)
    shutil.copy2(_HELPER_SOURCE, cache / "lib" / "bash-helpers.sh")

    # ~/Documents/Paper-Wiki — empty stub vault.
    (home / "Documents" / "Paper-Wiki").mkdir(parents=True, exist_ok=True)

    return home
